name: design_challenge
description: "JP Design Challenge."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.1
  go_router: ^16.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/bg/
    - assets/images/ingredients/
    - assets/fonts/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter_28pt-Black.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter_28pt-SemiBold.ttf
          weight: 900
